spring.application.name=movie
spring.data.mongodb.uri=mongodb+srv://vsss:newuser123%23%40@cluster0.wzexsa3.mongodb.net/moviedb?retryWrites=true&w=majority&serverSelectionTimeoutMS=5000
server.port=5000


